/* Base de joueurs (personnes), curée manuellement.
   Champs : n=nom, t=titre, c=pays (ISO2 pour le drapeau),
            cc=pseudo Chess.com, li=pseudo Lichess (uniquement si connus avec certitude),
            w=titre de l'article Wikipédia (défaut = n), note=repère court.
   Édite librement ce fichier pour ajouter des joueurs ou corriger un compte. */
window.PLAYERS = [
  {n:"Magnus Carlsen", t:"GM", c:"NO", cc:"MagnusCarlsen", li:"DrNykterstein", note:"Champion du monde 2013-2023"},
  {n:"Hikaru Nakamura", t:"GM", c:"US", cc:"Hikaru", note:"Multiple champion du monde de blitz"},
  {n:"Fabiano Caruana", t:"GM", c:"US", cc:"FabianoCaruana", note:"Challenger du titre en 2018"},
  {n:"Ian Nepomniachtchi", t:"GM", c:"RU", cc:"lachesisq", note:"Double challenger du titre mondial"},
  {n:"Ding Liren", t:"GM", c:"CN", note:"Champion du monde 2023-2024"},
  {n:"Gukesh Dommaraju", t:"GM", c:"IN", w:"Gukesh Dommaraju", note:"Champion du monde 2024"},
  {n:"Alireza Firouzja", t:"GM", c:"FR", cc:"Firouzja2003", li:"alireza2003"},
  {n:"Wesley So", t:"GM", c:"US", cc:"GMWSO"},
  {n:"Anish Giri", t:"GM", c:"NL", cc:"AnishGiri"},
  {n:"Levon Aronian", t:"GM", c:"US", cc:"LevonAronian"},
  {n:"Rameshbabu Praggnanandhaa", t:"GM", c:"IN", w:"Rameshbabu Praggnanandhaa"},
  {n:"Arjun Erigaisi", t:"GM", c:"IN"},
  {n:"Vidit Gujrathi", t:"GM", c:"IN"},
  {n:"Nodirbek Abdusattorov", t:"GM", c:"UZ"},
  {n:"Vincent Keymer", t:"GM", c:"DE"},
  {n:"Wei Yi", t:"GM", c:"CN"},
  {n:"Nihal Sarin", t:"GM", c:"IN", cc:"nihalsarin2004", li:"nihalsarin"},
  {n:"Daniel Naroditsky", t:"GM", c:"US", cc:"DanielNaroditsky"},
  {n:"Richárd Rapport", t:"GM", c:"RO", w:"Richárd Rapport"},
  {n:"Jan-Krzysztof Duda", t:"GM", c:"PL", w:"Jan-Krzysztof Duda"},
  {n:"Garry Kasparov", t:"GM", c:"RU", cc:"GarryKasparov", note:"Champion du monde 1985-2000"},
  {n:"Vladimir Kramnik", t:"GM", c:"RU", cc:"VladimirKramnik", note:"Champion du monde 2000-2007"},
  {n:"Viswanathan Anand", t:"GM", c:"IN", note:"Champion du monde 2007-2013"},
  {n:"Anatoli Karpov", t:"GM", c:"RU", w:"Anatoli Karpov", note:"Champion du monde 1975-1985"},
  {n:"Bobby Fischer", t:"GM", c:"US", note:"Champion du monde 1972-1975"},
  {n:"Mikhaïl Tal", t:"GM", c:"LV", w:"Mikhaïl Tal", note:"Champion du monde 1960-1961"},
  {n:"José Raúl Capablanca", t:"GM", c:"CU", w:"José Raúl Capablanca", note:"Champion du monde 1921-1927"},
  {n:"Alexandre Alekhine", t:"GM", c:"FR", w:"Alexandre Alekhine", note:"Champion du monde 1927-1935, 1937-1946"},
  {n:"Emanuel Lasker", t:"GM", c:"DE", note:"Champion du monde 1894-1921"},
  {n:"Wilhelm Steinitz", t:"GM", c:"AT", note:"Premier champion du monde officiel"},
  {n:"Paul Morphy", t:"", c:"US", note:"Génie américain du XIXe siècle"},
  {n:"Tigran Petrossian", t:"GM", c:"AM", w:"Tigran Petrossian", note:"Champion du monde 1963-1969"},
  {n:"Boris Spassky", t:"GM", c:"RU", w:"Boris Spassky", note:"Champion du monde 1969-1972"},
  {n:"Mikhaïl Botvinnik", t:"GM", c:"RU", w:"Mikhaïl Botvinnik"},
  {n:"Judit Polgár", t:"GM", c:"HU", w:"Judit Polgár", note:"Meilleure joueuse de l'histoire"},
  {n:"Hou Yifan", t:"GM", c:"CN", note:"Championne du monde féminine"},
  {n:"Ju Wenjun", t:"GM", c:"CN", note:"Championne du monde féminine"},
  {n:"Aleksandra Goriatchkina", t:"GM", c:"RU", w:"Aleksandra Goriatchkina"},
  {n:"Humpy Koneru", t:"GM", c:"IN"},
  {n:"Alexandra Kosteniuk", t:"GM", c:"CH", w:"Alexandra Kosteniuk"}
];
